// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyD-p2EeXwI20TljJWP6DVwaJwSSLAkrQ',
    appId: '1:939836761543:web:05aa1715a5f21961ba65e2',
    messagingSenderId: '939836761543',
    projectId: 'cricket-scoring-1fbdb',
    authDomain: 'cricket-scoring-1fbdb.firebaseapp.com',
    storageBucket: 'cricket-scoring-1fbdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsX_MzpPBI_zlZBn40YzThmS-e9xINevs',
    appId: '1:939836761543:android:77a147b9dc494c1fba65e2',
    messagingSenderId: '939836761543',
    projectId: 'cricket-scoring-1fbdb',
    storageBucket: 'cricket-scoring-1fbdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQcBf5mE7oh9h2ErDRFd1p8wnWaP-2VLw',
    appId: '1:939836761543:ios:482735170a0d40a0ba65e2',
    messagingSenderId: '939836761543',
    projectId: 'cricket-scoring-1fbdb',
    storageBucket: 'cricket-scoring-1fbdb.firebasestorage.app',
    iosBundleId: 'com.example.cricketScoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQcBf5mE7oh9h2ErDRFd1p8wnWaP-2VLw',
    appId: '1:939836761543:ios:482735170a0d40a0ba65e2',
    messagingSenderId: '939836761543',
    projectId: 'cricket-scoring-1fbdb',
    storageBucket: 'cricket-scoring-1fbdb.firebasestorage.app',
    iosBundleId: 'com.example.cricketScoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyD-p2EeXwI20TljJWP6DVwaJwSSLAkrQ',
    appId: '1:939836761543:web:7b8c99282644e1c9ba65e2',
    messagingSenderId: '939836761543',
    projectId: 'cricket-scoring-1fbdb',
    authDomain: 'cricket-scoring-1fbdb.firebaseapp.com',
    storageBucket: 'cricket-scoring-1fbdb.firebasestorage.app',
  );

}